### ISSUE TITLE
Invalid date in metadata for layer

### ISSUE THREAD

**Issue by drh-stanford** [OpenGeoMetadata/edu.columbia#1]
See https://github.com/OpenGeoMetadata/edu.columbia/blob/master/sudanadmn4/geoblacklight.json#L12

```
ERROR: #<RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: 'Invalid Date in Date Math String:\'2007-00-52T00:00:00Z\'','code'=>400}}

```

**Comment by marquis** [comment]
Thanks for the report.  We've corrected the metadata and updated the repo.  We also scanned the rest of our records and didn't spot any other invalid dates - but please let us know if something turns up.
