### ISSUE TITLE
Unavailable WMS services for some layers

### ISSUE THREAD

**Issue by mejackreed** [OpenGeoMetadata/edu.columbia#2]
Hi @marquis . We were running some availability checks on your webservices and notices that 198 layers were unavailable. There are the ones we had issues with: 

https://gist.github.com/mejackreed/d1f229ebc76a8cf168b4b4864a18eacd

I hope this is helpful!

**Comment by marquis** [comment]
I've updated the Columbia metadata with the most recent copy provided to me by our GIS librarian.

Could you rerun your availability checks and let me know the results?
What are you using to do this check - maybe I can just run this internally?

**Comment by mejackreed** [comment]
Thanks @marquis . We are using [GeoMonitor](https://github.com/geoblacklight/geo_monitor) to run status checks on layers. The idea is that it should simulate a WMS tile request. An example request that is being created:

```https://geodata.library.columbia.edu/geoserver/wms/sde?BBOX=-20037508.342789244%2C0.0%2C0.0%2C20037508.342789274&CRS=EPSG%3A900913&FORMAT=image%2Fpng&HEIGHT=256&LAYERS=sde%3Acolumbia.worldports2012&REQUEST=GetMap&SERVICE=WMS&SRS=EPSG%3A3857&STYLES=&TILED=true&VERSION=1.1.1&WIDTH=256```
You can most definitely run the check internally. 

```ruby
layer = GeoMonitor::Layer.from_geoblacklight(geoblacklight_json)
layer.check
```

Perhaps we are referencing the wrong url? Looking at the URL we are using I think maybe we need to modify it:

```diff
+ https://geoserver.cul.columbia.edu/geoserver/wms/sde?BBOX=-20037508.342789244%2C0.0%2C0.0%2C20037508.342789274&CRS=EPSG%3A900913&FORMAT=image%2Fpng&HEIGHT=256&LAYERS=sde%3Acolumbia.worldports2012&REQUEST=GetMap&SERVICE=WMS&SRS=EPSG%3A3857&STYLES=&TILED=true&VERSION=1.1.1&WIDTH=256
- https://geodata.library.columbia.edu/geoserver/wms/sde?BBOX=-20037508.342789244%2C0.0%2C0.0%2C20037508.342789274&CRS=EPSG%3A900913&FORMAT=image%2Fpng&HEIGHT=256&LAYERS=sde%3Acolumbia.worldports2012&REQUEST=GetMap&SERVICE=WMS&SRS=EPSG%3A3857&STYLES=&TILED=true&VERSION=1.1.1&WIDTH=256
```
cc @drh-stanford

**Comment by marquis** [comment]
Yesterday's update should have corrected the server URL from geodata.library to geoserver.cul.

I've pushed another update today to remove GeoServer references from all Raster layers.  Apparently we have these available for download, but not accessible via GeoServer.

I'm hoping that these two corrections should clear up the issues.

Unfortunately, I've not yet bumped our local GeoBlacklight to Rails 5, and so can't use geo_monitor yet.  I'll try to get that done soon, though, it looks like a super useful validation tool.

**Comment by mejackreed** [comment]
Amazing! Thanks so much for the quick feedback @marquis :) Closing this issue for now.
